# SPDX-FileCopyrightText: 2022 Pablo Hörtner
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Copyright © 2022 by Pablo Hörtner <redtux@pm.me>. All rights reserved.
# You can find the AGPL v3.0 here: https://www.gnu.org/licenses/agpl-3.0
#
# License Compliance Check · redgnus
# https://github.com/fsfe/reuse-action#readme
name: License Compliance Check

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
